version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing Nodejs"
  build:
    commands:
      - cp hello-world.js /tmp/hello-world.js

artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR
  discard-paths: no
