version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing Nodejs"
  build:
    commands:
      - node hello-world.js

artifacts:
  files:
    - hello-world.js
  base-directory: $CODEBUILD_SRC_DIR
  discard-paths: no
